function FileData_Pairs(x)
{
x.t("every","page");
x.t("description","link");
x.t("cadsr","sentinel");
x.t("sentinel","tool");
x.t("displays","tool");
x.t("browser","window");
x.t("text","displays");
x.t("link","cases");
x.t("new","browser");
x.t("footer","banners");
x.t("images","text");
x.t("retains","sentinel");
x.t("window","retains");
x.t("moving","mouse");
x.t("consistently","every");
x.t("mouse","images");
x.t("opens","new");
x.t("header","footer");
x.t("appear","consistently");
x.t("selecting","links");
x.t("page","sentinel");
x.t("page","display");
x.t("tip","description");
x.t("tool","moving");
x.t("tool","tip");
x.t("tool","page");
x.t("tool","banners");
x.t("banners","header");
x.t("banners","appear");
x.t("banners","banners");
x.t("banners","using");
x.t("cases","selecting");
x.t("links","opens");
x.t("using","cadsr");
}
