function FileData_Pairs(x)
{
x.t("internet","explorer");
x.t("version","6.0");
x.t("cde","sentinel");
x.t("cadsr","curation");
x.t("sentinel","tool");
x.t("bar","select");
x.t("open","internet");
x.t("browser","address");
x.t("link","cde");
x.t("menu","application");
x.t("url","http://cdecurate.nci.nih.gov");
x.t("welcome","cadsr");
x.t("address","bar");
x.t("6.0","higher");
x.t("select","link");
x.t("options","menu");
x.t("http://cdecurate.nci.nih.gov","browser");
x.t("accessing","sentinel");
x.t("login","page");
x.t("enter","url");
x.t("curation","tool");
x.t("online","help");
x.t("help","accessing");
x.t("page","open");
x.t("tool","welcome");
x.t("tool","options");
x.t("tool","accessing");
x.t("tool","enter");
x.t("tool","online");
x.t("application","login");
x.t("explorer","version");
x.t("higher","certified");
}
