function FileData_Pairs(x)
{
x.t("dates","dates");
x.t("dates","date");
x.t("dates","using");
x.t("within","sentinel");
x.t("cadsr","sentinel");
x.t("always","interpreted");
x.t("sentinel","tool");
x.t("today","starting");
x.t("yesterday","starting");
x.t("yesterday's","date");
x.t("cover","changes");
x.t("alert","cover");
x.t("interpreted","midnight");
x.t("starting","date");
x.t("changes","made");
x.t("alerts","always");
x.t("made","today");
x.t("made","yesterday");
x.t("midnight","midnight");
x.t("midnight","manually");
x.t("tool","dates");
x.t("tool","alerts");
x.t("date","yesterday's");
x.t("date","today's");
x.t("date","tomorrow's");
x.t("date","ending");
x.t("date","manually");
x.t("date","ranges");
x.t("today's","date");
x.t("tomorrow's","date");
x.t("run","alert");
x.t("ending","date");
x.t("using","cadsr");
x.t("manually","run");
x.t("ranges","within");
}
